// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYzm9BXXNtkffVRzqwcz-ZR_H4vwOITo0',
    appId: '1:352858476035:web:2b67efb1edbd9edaf7c836',
    messagingSenderId: '352858476035',
    projectId: 'tunexa-social-app',
    authDomain: 'tunexa-social-app.firebaseapp.com',
    storageBucket: 'tunexa-social-app.firebasestorage.app',
    measurementId: 'G-T6L0XMW1DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRO9MP5YKmVj-_UDnqn_B7EJF0RH44FGA',
    appId: '1:352858476035:android:1bb00b3a5a9978f7f7c836',
    messagingSenderId: '352858476035',
    projectId: 'tunexa-social-app',
    storageBucket: 'tunexa-social-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSSLZOmtCf257LfhJSRMXxiKGohfrPl1k',
    appId: '1:352858476035:ios:f63ec083c14c7726f7c836',
    messagingSenderId: '352858476035',
    projectId: 'tunexa-social-app',
    storageBucket: 'tunexa-social-app.firebasestorage.app',
    iosBundleId: 'com.example.tunexaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSSLZOmtCf257LfhJSRMXxiKGohfrPl1k',
    appId: '1:352858476035:ios:f63ec083c14c7726f7c836',
    messagingSenderId: '352858476035',
    projectId: 'tunexa-social-app',
    storageBucket: 'tunexa-social-app.firebasestorage.app',
    iosBundleId: 'com.example.tunexaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYzm9BXXNtkffVRzqwcz-ZR_H4vwOITo0',
    appId: '1:352858476035:web:deb7e53e8b7f3438f7c836',
    messagingSenderId: '352858476035',
    projectId: 'tunexa-social-app',
    authDomain: 'tunexa-social-app.firebaseapp.com',
    storageBucket: 'tunexa-social-app.firebasestorage.app',
    measurementId: 'G-G1K0JXN0NX',
  );

}